version: '3.4'
services:

  ipfs:
    restart: always
    container_name: "ecta-ipfs"
    image: ipfs/go-ipfs:v0.7.0
    environment:
      - IPFS_PROFILE=server
    ports:
      # 4001 is the ipfs swarm port and needs to be open to the world. If you are running a firewall you should unblock that port. (P2P TCP/QUIC transports)
      # host 8180 -> 8080 is the local gateway which will we expose only to localhost,  (Gateway):
      # host 8181 -> 8081 is where we are going to run the websocket listener – we will proxy through nginx, 
      # host 8560 -> 5001 is the api server which should not be exposed externally. (RPC API) and WebUi http://localhost:8560/webui
      - "4001:4001"
      - "127.0.0.1:8180:8080" # 8180 8080
      #- "127.0.0.1:8181:8081"
      - "127.0.0.1:8560:5001" #5001 8560
    volumes:
      - ipfsdata:/data/ipfs
      #- ./compose/local/ipfs/start_ipfs:/usr/local/bin/start_ipfs


volumes:
  ipfsdata:

